### PR TITLE
WIP: cite: fixes modal to look like qa.inspirehep.net

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Addresses https://github.com/inspirehep/inspirehep-js/issues/1/

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
@jmartinm this one goes together with this one https://github.com/inspirehep/inspirehep-search-js/pull/7 .  
When the time comes, we will merge them together.

**Comment by ioannistsanaktsidis** [comment]
WARNING: When the time comes merge this one alongside with https://github.com/inspirehep/inspire-next/pull/1063 and https://github.com/inspirehep/inspirehep-search-js/pull/7. ;)

**Comment by ioannistsanaktsidis** [comment]
I guess @Panos512 will now take care of the rest. Cheers. ;)

**Comment by jmartinm** [comment]
superseded by https://github.com/inspirehep/inspirehep-js/pull/7

**Pull request closed without merging**
